{% set name = "gufe" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/gufe/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 61ab69e6427192baab3730e3174cc3151982effb9ac6d296f2ac771268db1593

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - coverage
    - networkx
    - numpy <1.24.0
    - openff-toolkit
    - openff-units >=0.2.0
    - openff-models >=0.0.4
    - pip
    - python >=3.9
    - rdkit
    - typing-extensions

test:
  imports:
    - gufe
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v --pyargs gufe

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: 'gufe: Grand Unified Free Energy'
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/OpenFreeEnergy/gufe
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
    - dotsdl
